enum Features {
  ACHIEVEMENTS = 'FF_ACHIEVEMENTS',
  RESUME = 'FF_RESUME',
  BLOG = 'FF_BLOG',
  OSS_PROJECTS = 'FF_OSS_PROJECTS',
  BOOKS = 'FF_BOOKS',
  PROJECTS = 'FF_PROJECTS',
  RECOMMENDATIONS = 'FF_RECOMMENDATIONS',
  PINNED_PROJECTS = 'FF_PINNED_PROJECTS',
  SNIPPETS = 'FF_SNIPPETS',
  USES = 'FF_USES',
  FAQ = 'FF_FAQ',
  EXERCISES = 'FF_EXERCISES',
}

export { Features }
