// @ts-ignore: we need to ignore the missing namespace error.
import env from '~/utils/env'

// @ts-ignore: these content will be generated by the build process.
import { allBlogs as allBlogsContent } from '.contentlayer/data'
// @ts-ignore: this type will be generated by the build process.
import type { Blog } from '.contentlayer/types'

const allBlogs = (env.FF_PROJECTS ? allBlogsContent ?? [] : []) as Blog[]

export type { Blog }

export { allBlogs }
