name: CI

on: push

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.17.0

      - name: Cache node modules
        id: node-modules
        uses: actions/cache@v1.2.0
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - run: tar -zcf node_modules.tar.gz node_modules

      - uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules.tar.gz
          retention-days: 1

  testing:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: 'mysql://githubci:githubci@127.0.0.1:3306/personal_website'
      SHADOW_DATABASE_URL: 'mysql://githubci:githubci@127.0.0.1:3306/personal_website'
      AUTH_JWT_SECRET: deamon

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.17.0]

    needs: [install_dependencies]

    steps:
      - name: Setup Database with Mysql
        run: |
          docker run \
          --name mysql \
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
          -e MYSQL_DATABASE=personal_website \
          -e MYSQL_USER=githubci \
          -e MYSQL_PASSWORD=githubci \
          --health-cmd='mysqladmin ping' \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=5 \
          -p 3306:3306 \
          -d mysql:8.0.13 \
          --sql-mode='' \
          --default-authentication-plugin='mysql_native_password' \

      - name: Checkout Repo
        uses: actions/checkout@v2.1.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: node-modules

      - name: Install Cache Dependencies
        run: tar -zxf node_modules.tar.gz

      - name: Wait for MySQL
        run: npx wait-on tcp:3306 && echo "MySQL is up"

      - name: Build
        run: npm run contentlayer:build

      - name: Static Testing
        run: npm run test:static

      - name: Unit Testing
        run: npm run test:unit:ci
